### ISSUE TITLE
[16:12:03] [ManzanaCore] ERROR: URL is invalid!

### ISSUE THREAD

**Issue by alexdeve01** [dropcreations/Manzana-Apple-Music-Lyrics#1]
Hi! When I enter the url, this error pops up:

[16:12:03] [ManzanaCore] ERROR: URL is invalid!

The link was this: https://music.apple.com/us/album/guts/1694386825

The full command was: python3 manzana.py --sync --no-lrc https://music.apple.com/es/album/cerdicienta-banda-sonora-de-la-pel%C3%ADcula-ep/1642983033

How can I fix this? Thank you! :)

**Comment by dropcreations** [comment]
@alexdeve01 Is there the same error for song or music-video URLs?

and one more thing: `--sync` is useless with `--no-lrc`. The `--sync` command is used to change the .lrc file's timecodes.

**Comment by alexdeve01** [comment]
Hi! Yes, it is.

**Comment by dropcreations** [comment]
@alexdeve01 Did you add more to the code? or what's the process you followed? The full command you mentioned above is also working fine.

**Comment by alexdeve01** [comment]
No, I just enter the command I mentioned and this appear:

[13:46:45] [ManzanaCore] INFO: Checking access token found in cache...
[13:46:45] [ManzanaCore] INFO: Checking media-user-token...
[13:46:45] [ManzanaCore] ERROR: URL is invalid!

**Comment by dropcreations** [comment]
@alexdeve01 Mail me: dropcodestudio@gmail.com
